### ISSUE TITLE
Logos in vector graphics!

### ISSUE THREAD

**Issue by cciliber** [robotology/iCubWorld#1]
Currently logo images are in png. We need to change them to svg or pdf asap

**Comment by alecive** [comment]
Do you mean the icubWorld logo? I think I gave it to you in SVG format.

**Comment by cciliber** [comment]
The iCubWorld logo is one of them indeed. 

Yes, I should have the svg somewhere (although for some reason a quick search didn't find anything). The issue is exactly to remind us to do switch logos from pixel to vector.

**Comment by alecive** [comment]
..which is something that I already told you back in the day :stuck_out_tongue: 

btw, since I'm more organized than you, I come to your rescue with this link https://github.com/alecive/iCubArtwork/blob/master/iCub-Icon/iCub_World_solidcolor.svg

**Comment by cciliber** [comment]
Grazie <3
